spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}AQBCirPjTtvbSrBSbItQo2+/cQRRSpMyCd0jhgK2IoA+SEr03wknr83glIhLKW38JBUovZouBkpmXz4DSA9pNF4Z8s61IBZQJxGlXxCSS3Qgg4qCW0ZR/apFUoAMxhaiNG2khw9jgPRe7hzlyNTilWwxTb7XyEzwIdczGbQ/t+3MoKT9Rx2Obwuv9c7cyV4tvLpOiQIWy1ve9bOHaq1TAkvWbVfIe9Q82QF/uVeuAHKibgeOia4wSrwHCmgiw+BFnvVBexbzMo3DOEWNSkR1X/A1xdk1bu4WVKFhmThBtn8pN12IbuXrNUGa+NUAhZlP6Rllsq3ESqUCn63UqZ7p6jlSPlIn1IQ2S7llxyht0J0hlIvYgamEhDrVXlV6PGpJP6o='

token:
  expiration_time: 864000000
#  secret: user_token_native_user_service -> user_token_native_ecommerce
  secret: '{cipher}AQBkBbrok0qzgSr5utmJ32heZt5D9nEaEEQSuLTUez2ffCzj9ShzRhkih44rvfP86WRESZLQb44Pznt3gLfDd+Wq7UPW0Ok1qXY7w+m3yhoVOOwBj+uQXdrATqtFNM4NcO7PPNQDcPZ8dYV6HeOx8eArlZgaEUsrZERUz7eY56KDsvSD4z+5nJj0MBdLcBiEwvo6r9UbH6RN9ywItdaYyt5InBunOva1po9D/vujSRE8VaNuKcPeovzS1h6xqGAZZ/9DLYXj4NgX1AzapaKKDUFEN31o0O1U2p+71w77MuOkjQyrROxVAmq2B+tXU5MPW/vibUbu4BW24TnNjJyXloOv7EKOsrGy/eFa/6go8S0jKZ8vnIa1xLJ4VufWSOfjLVyVMJm8gQW5FoZBLQjPwnhc'

gateway:
  ip: 172.18.0.5 # 127.0.0.1

order_service:
# @LoadBalanced 적용 전
#  url: http://127.0.0.1:8000/order-service/%s/orders
# @LoadBalanced 적용 후
  url: http://ORDER-SERVICE/order-service/%s/orders
  exception:
    #orders_is_empty: User's orders is empty.
    orders_is_empty: There is no item.
